# Generated by Django 4.1.7 on 2023-03-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="temptdata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rollnum_1", models.CharField(max_length=20)),
                ("rollnum_2", models.CharField(max_length=20)),
                ("name_1", models.CharField(max_length=100)),
                ("name_2", models.CharField(max_length=100)),
                ("in_time", models.DateTimeField(max_length=100)),
            ],
        ),
    ]
